# Generated by Django 5.1.7 on 2025-04-04 23:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_alter_user_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='google_id',
        ),
        migrations.RemoveField(
            model_name='user',
            name='image',
        ),
    ]
