# Generated by Django 5.2 on 2025-04-11 14:06

import account.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0011_alter_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='last_active',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='code',
            name='code',
            field=models.CharField(blank=True, help_text='code', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='code',
            name='expired_data',
            field=models.DateTimeField(default=account.models.time_default, help_text='expired data'),
        ),
        migrations.AlterField(
            model_name='code',
            name='user',
            field=models.ForeignKey(help_text='user', on_delete=django.db.models.deletion.CASCADE, related_name='code_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='profile',
            name='bio',
            field=models.CharField(blank=True, help_text='bio', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(blank=True, default='profile_images/default.jpg', help_text='image', null=True, upload_to='profile_images'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='phone_number',
            field=models.CharField(blank=True, help_text='phone number', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(help_text='user', on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(help_text='Email address', max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(blank=True, help_text='username', max_length=255, null=True),
        ),
    ]
