# Generated by Django 5.2 on 2025-04-11 14:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('money', '0002_alter_category_name_alter_expense_description_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Category', 'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='expense',
            options={'verbose_name': 'Expense', 'verbose_name_plural': 'Expenses'},
        ),
        migrations.AlterModelOptions(
            name='income',
            options={'verbose_name': 'Income', 'verbose_name_plural': 'Incomes'},
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(help_text='name', max_length=100, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='category',
            name='user_id',
            field=models.ForeignKey(help_text='user', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='expense',
            name='amount',
            field=models.DecimalField(decimal_places=2, help_text='amount', max_digits=100, verbose_name='amount'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='category',
            field=models.ForeignKey(help_text='category', on_delete=django.db.models.deletion.CASCADE, to='money.category'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='created_at',
            field=models.DateField(auto_now_add=True, help_text='created at', verbose_name='created_at'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='description',
            field=models.TextField(help_text='description', verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='is_deleted',
            field=models.BooleanField(default=False, help_text='is deleted', verbose_name='is deleted'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='user_id',
            field=models.ForeignKey(help_text='user', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='income',
            name='amount',
            field=models.DecimalField(decimal_places=2, help_text='amount', max_digits=100),
        ),
        migrations.AlterField(
            model_name='income',
            name='category',
            field=models.ForeignKey(help_text='category', on_delete=django.db.models.deletion.CASCADE, to='money.category'),
        ),
        migrations.AlterField(
            model_name='income',
            name='created_at',
            field=models.DateField(auto_now_add=True, help_text='created at'),
        ),
        migrations.AlterField(
            model_name='income',
            name='description',
            field=models.TextField(help_text='description', verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='income',
            name='is_deleted',
            field=models.BooleanField(default=False, help_text='is deleted'),
        ),
        migrations.AlterField(
            model_name='income',
            name='user_id',
            field=models.ForeignKey(help_text='user', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
