# Generated by Django 5.2 on 2025-04-11 17:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('money', '0005_alter_files_file'),
    ]

    operations = [
        migrations.RenameField(
            model_name='files',
            old_name='user_id',
            new_name='user',
        ),
    ]
