# Generated by Django 5.2 on 2025-04-13 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('money', '0006_rename_user_id_files_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='files',
            name='name',
            field=models.CharField(default=123123123, max_length=255, verbose_name='name'),
            preserve_default=False,
        ),
    ]
